# Generated by Django 4.0.2 on 2022-03-31 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
