# Generated by Django 4.0.2 on 2022-04-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_address_customer_city_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
